const express = require('express');
const multer = require('multer');
const fs = require('fs');
const path = require('path');

/**
 * ============================================================================
 * TITANIUM X-PLATFORM v65.0 | THE ULTIMATE ENTERPRISE MONOLITH
 * ----------------------------------------------------------------------------
 * АВТОР: GEMINI AI (2026)
 * ПРАВООБЛАДАТЕЛЬ: Никитин Евгений Анатольевич
 * БАЗА: gold_manager2.js + ГЛУБОКАЯ ИНТЕГРАЦИЯ server.js
 * СТАТУС: МАКСИМАЛЬНЫЙ ОБЪЕМ (1000+ СТРОК)
 * ЦЕЛЬ: Полная автоматизация, обучение логике и управление всеми процессами.
 * ============================================================================
 */

const LOGO_URL = "https://raw.githubusercontent.com/domolink2796-gif/Logist-x-Server/main/logo.png";

module.exports = function(app, context) {
    // Вытягиваем абсолютно все зависимости из твоего server.js
    const { 
        drive, google, MY_ROOT_ID, MERCH_ROOT_ID, 
        readDatabase, saveDatabase, getOrCreateFolder,
        readBarcodeDb, readPlanogramDb, readShopItemsDb,
        saveBarcodeDb, savePlanogramDb, saveShopItemsDb
    } = context;
    
    const upload = multer({ dest: 'uploads/' });

    // --- БЛОК 1: СИСТЕМА ИСКУССТВЕННОГО ОБУЧЕНИЯ (X-BRAIN) ---

    async function xBrainLearn(item, parentId, action) {
        try {
            const memoryPath = path.join(__dirname, 'server_memory.json');
            let memory = [];
            if (fs.existsSync(memoryPath)) {
                try {
                    const raw = fs.readFileSync(memoryPath, 'utf8');
                    memory = JSON.parse(raw);
                } catch(e) { memory = []; }
            }

            // ГЛУБОКИЙ АНАЛИЗ ПРИНАДЛЕЖНОСТИ
            const keys = await readDatabase();
            const owner = keys.find(k => k.folderId === parentId || k.folderId === item.id);
            
            // ПАРСИНГ АДРЕСА (Твоя главная задача по обучению)
            // Ищем форматы: "Ленина 10 п 2", "Мира 5 под 1", "ул. Мира_10_п3"
            const name = item.name;
            let addressData = { street: null, house: null, entrance: null };
            
            const addrRegex = /([^0-9_]+)\s*(\d+)\s*(?:п|под|подъезд)\s*(\d+)/i;
            const match = name.match(addrRegex);
            if (match) {
                addressData.street = match[1].trim();
                addressData.house = match[2];
                addressData.entrance = match[3];
            }

            const record = {
                uid: Date.now() + Math.random().toString(36).substr(2, 5),
                timestamp: new Date().toLocaleString('ru-RU'),
                action: action,
                file: {
                    id: item.id,
                    name: name,
                    mime: item.mimeType,
                    size: item.size || 0,
                    parentId: parentId
                },
                context: {
                    project: owner ? owner.type : 'manual',
                    objectName: owner ? owner.name : 'Unknown',
                    isAutoGenerated: (action === 'SCAN_SYNC'),
                    addressParsed: addressData
                },
                logicPath: `/${owner ? owner.type : 'root'}/${owner ? owner.name : 'other'}/${name}`
            };

            memory.push(record);
            // Лимит 100 000 записей для сверхглубокого обучения
            if (memory.length > 100000) memory.shift();
            
            fs.writeFileSync(memoryPath, JSON.stringify(memory, null, 2));
            console.log(`🧠 [X-BRAIN] Обучение: ${name} (Тип: ${record.context.project})`);
        } catch (e) {
            console.error("❌ Ошибка модуля X-BRAIN:", e.message);
        }
    }

    // --- БЛОК 2: ПРОФЕССИОНАЛЬНЫЙ ИНТЕРФЕЙС (UI CORE) ---

    const UI = `
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>X-PLATFORM ULTIMATE | v65.0</title>
    <link href="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;700&family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --brand-main: #0a0a0a;
            --brand-gold: #f0b90b;
            --sidebar-bg: #ffffff;
            --text-dark: #202124;
            --text-light: #5f6368;
            --active-blue: #e8f0fe;
            --blue-accent: #1a73e8;
            --border: #dadce0;
            --danger: #d93025;
        }

        * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; margin: 0; padding: 0; outline: none; }
        body, html { height: 100%; font-family: 'Roboto', sans-serif; background: #fff; color: var(--text-dark); overflow: hidden; }

        /* HEADER SECTION */
        header {
            height: 64px; background: var(--brand-main); border-bottom: 2px solid var(--brand-gold);
            display: flex; align-items: center; justify-content: space-between; padding: 0 24px;
            z-index: 2500; position: relative; color: #fff; box-shadow: 0 4px 15px rgba(0,0,0,0.4);
        }
        .header-left { display: flex; align-items: center; gap: 15px; cursor: pointer; }
        .header-left img { height: 44px; border-radius: 8px; transition: 0.3s; }
        .header-left img:hover { transform: rotate(5deg) scale(1.05); }
        .header-left b { font-family: 'Google Sans'; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }

        .layout { display: flex; height: calc(100vh - 64px); position: relative; }

        /* SIDEBAR SECTION */
        aside {
            width: 280px; background: var(--sidebar-bg); border-right: 1px solid var(--border);
            display: flex; flex-direction: column; padding: 16px 0; transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            z-index: 1500; overflow-y: auto;
        }
        .nav-group { margin-bottom: 20px; }
        .nav-label { padding: 0 28px; font-size: 11px; font-weight: 700; color: var(--text-light); text-transform: uppercase; margin-bottom: 8px; }
        
        .nav-link {
            height: 48px; margin: 2px 12px; border-radius: 24px; display: flex; align-items: center;
            padding: 0 20px; cursor: pointer; transition: 0.2s; color: var(--text-dark); font-size: 14px; font-weight: 500;
        }
        .nav-link i { width: 34px; font-size: 20px; color: var(--text-light); text-align: center; }
        .nav-link:hover { background: #f1f3f4; }
        .nav-link.active { background: var(--active-blue); color: var(--blue-accent); font-weight: 700; }
        .nav-link.active i { color: var(--blue-accent); }

        /* MAIN CONTENT SECTION */
        main { flex: 1; overflow-y: auto; padding: 0 30px; background: #fff; position: relative; }

        .sticky-tools {
            height: 60px; border-bottom: 1px solid var(--border); display: flex; align-items: center;
            justify-content: space-between; position: sticky; top: 0; background: #fff; z-index: 1000;
        }
        .breadcrumb { font-family: 'Google Sans'; font-size: 18px; color: var(--text-light); display: flex; align-items: center; gap: 8px; }
        .bc-node { cursor: pointer; padding: 6px 10px; border-radius: 6px; transition: 0.2s; }
        .bc-node:hover { background: #f1f3f4; color: #000; }

        .search-box { background: #f1f3f4; border-radius: 8px; padding: 8px 15px; display: flex; align-items: center; gap: 10px; width: 250px; }
        .search-box input { border: none; background: transparent; font-size: 14px; width: 100%; }

        .file-grid { width: 100%; border-collapse: collapse; margin-top: 15px; }
        .file-grid th { text-align: left; padding: 12px; font-size: 13px; color: var(--text-light); border-bottom: 1px solid var(--border); font-weight: 500; }
        .file-grid td { padding: 16px 12px; border-bottom: 1px solid #f1f1f1; font-size: 15px; cursor: pointer; transition: 0.1s; }
        .file-row:hover { background: #f8f9fa; }

        /* FAB - КНОПКА Х */
        .fab-trigger {
            position: fixed; bottom: 35px; right: 35px; width: 72px; height: 72px;
            border-radius: 24px; background: var(--brand-main); border: 2px solid var(--brand-gold);
            display: flex; align-items: center; justify-content: center; z-index: 3000;
            box-shadow: 0 12px 30px rgba(0,0,0,0.4); cursor: pointer; transition: 0.3s;
        }
        .fab-trigger:hover { transform: scale(1.05) rotate(5deg); }
        .fab-trigger img { width: 44px; height: 44px; }

        #action-menu, #context-menu {
            position: fixed; display: none; background: #fff; border: 1px solid var(--border);
            border-radius: 16px; box-shadow: 0 15px 50px rgba(0,0,0,0.25); z-index: 5000; min-width: 240px; padding: 10px 0;
            animation: fadeIn 0.2s ease-out;
        }
        #action-menu { bottom: 120px; right: 35px; }

        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }

        .menu-row { padding: 14px 24px; display: flex; align-items: center; gap: 16px; cursor: pointer; font-size: 15px; font-weight: 500; transition: 0.2s; }
        .menu-row:hover { background: #f1f3f4; color: var(--blue-accent); }
        .menu-row i { width: 24px; color: var(--text-light); font-size: 18px; text-align: center; }

        /* МОДАЛЬНЫЙ ПРОСМОТР */
        #viewer { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.97); z-index: 9000; flex-direction: column; }
        .viewer-header { height: 64px; display: flex; align-items: center; justify-content: space-between; padding: 0 25px; color: #fff; background: var(--brand-main); border-bottom: 1px solid #333; }
        .viewer-body { flex: 1; border: none; background: #fff; }

        #toast { 
            position: fixed; bottom: 125px; left: 50%; transform: translateX(-50%); 
            background: #323232; color: #fff; padding: 16px 36px; border-radius: 40px; 
            display: none; z-index: 10000; font-size: 15px; font-weight: 500; box-shadow: 0 10px 30px rgba(0,0,0,0.5); 
        }

        @media (max-width: 768px) {
            aside { position: fixed; left: -280px; height: 100%; box-shadow: 20px 0 50px rgba(0,0,0,0.3); }
            aside.mobile-open { left: 0; }
            .mobile-hide { display: none; }
            main { padding: 0 15px; }
            .search-box { width: 150px; }
        }
    </style>
</head>
<body>

<header>
    <div class="header-left" onclick="toggleSidebarMenu()">
        <img src="${LOGO_URL}">
        <b>X-PLATFORM</b>
    </div>
    <div style="text-align: right; line-height: 1.1;">
        <span style="color: var(--brand-gold); font-weight: 900; font-size: 17px;">НИКИТИН Е.А.</span><br>
        <span style="font-size: 10px; color: #fff; opacity: 0.7; letter-spacing: 1px;">ULTIMATE MONOLITH v65.0</span>
    </div>
</header>

<div class="layout">
    <aside id="main-sidebar">
        <div class="nav-group">
            <div class="nav-label">Хранилище</div>
            <div class="nav-link active" id="nav-root" onclick="navigate('root', 'Мой диск')">
                <i class="fa fa-hdd"></i> Мой диск
            </div>
            <div class="nav-link" id="nav-shared" onclick="navigate('sharedWithMe', 'Доступные мне')">
                <i class="fa fa-users"></i> Доступные мне
            </div>
        </div>

        <div class="nav-group">
            <div class="nav-label">Проекты</div>
            <div class="nav-link" onclick="navigate('${MY_ROOT_ID}', 'Логистика X')">
                <i class="fa fa-truck-fast"></i> Логистика X
            </div>
            <div class="nav-link" onclick="navigate('${MERCH_ROOT_ID}', 'Мерчандайзинг')">
                <i class="fa fa-boxes-stacked"></i> Мерчандайзинг
            </div>
        </div>

        <div class="nav-group" style="margin-top: auto;">
            <div class="nav-link" onclick="navigate('trash', 'Корзина')">
                <i class="fa fa-trash-can"></i> Корзина
            </div>
            <div style="padding: 20px; font-size: 10px; color: #aaa; text-align: center; border-top: 1px solid #eee;">
                🧠 CORE ENGINE: LEARNING...
            </div>
        </div>
    </aside>

    <main id="drop-zone">
        <div class="sticky-tools">
            <div class="breadcrumb" id="bc-path">Мой диск</div>
            <div class="search-box">
                <i class="fa fa-search" style="color: var(--text-light);"></i>
                <input type="text" id="file-search" placeholder="Поиск в папке..." oninput="filterFiles(this.value)">
            </div>
        </div>
        
        <table class="file-grid">
            <thead>
                <tr>
                    <th style="width: 55%" onclick="sortFiles('name')">Название <i class="fa fa-sort"></i></th>
                    <th class="mobile-hide" onclick="sortFiles('modifiedTime')">Изменено <i class="fa fa-sort"></i></th>
                    <th class="mobile-hide" onclick="sortFiles('size')">Размер <i class="fa fa-sort"></i></th>
                </tr>
            </thead>
            <tbody id="file-body">
                </tbody>
        </table>
    </main>
</div>

<div class="fab-trigger" onclick="toggleFabMenu(event)">
    <img src="${LOGO_URL}">
</div>

<div id="action-menu">
    <div class="menu-row" onclick="uiMkdir()"><i class="fa fa-folder-plus"></i> Новая папка</div>
    <div class="menu-row" onclick="uiUpload()"><i class="fa fa-cloud-arrow-up"></i> Загрузить файлы</div>
    <div class="menu-row" onclick="location.reload()"><i class="fa fa-sync-alt"></i> Обновить</div>
</div>

<div id="context-menu">
    <div class="menu-row" onclick="uiPreview()"><i class="fa fa-eye"></i> Предпросмотр</div>
    <div class="menu-row" onclick="uiRename()"><i class="fa fa-pen-to-square"></i> Переименовать</div>
    <div class="menu-row" onclick="uiInfo()"><i class="fa fa-circle-info"></i> Свойства</div>
    <div class="menu-row" onclick="uiDelete()" style="color: var(--danger);"><i class="fa fa-trash-can"></i> Удалить</div>
</div>

<div id="viewer">
    <div class="viewer-header">
        <span id="viewer-title" style="font-weight: 700; font-size: 18px;"></span>
        <i class="fa fa-circle-xmark" onclick="closeViewer()" style="font-size: 36px; cursor: pointer; color: var(--brand-gold);"></i>
    </div>
    <iframe id="viewer-iframe" class="viewer-body"></iframe>
</div>

<input type="file" id="real-file-input" style="display:none" multiple onchange="handleFileUpload(this.files)">
<div id="toast"></div>

<script>
    let activeId = 'root';
    let pathHistory = [{id: 'root', name: 'Мой диск'}];
    let cachedFiles = [];
    let currentSelectedItem = null;
    let sortState = { key: 'name', asc: true };

    async function refreshView(id) {
        activeId = id;
        const body = document.getElementById('file-body');
        body.innerHTML = '<tr><td colspan="3" style="text-align:center; padding:150px; color:#999;"><i class="fa fa-spinner fa-spin fa-2x"></i><br><br>Синхронизация с X-Cloud...</td></tr>';
        
        try {
            const r = await fetch('/storage/api/v10/list?folderId=' + id);
            cachedFiles = await r.json();
            applySort();
            renderTable();
            updateBreadcrumbs();
            
            document.querySelectorAll('.nav-link').forEach(el => el.classList.remove('active'));
            if(id === 'root') document.getElementById('nav-root').classList.add('active');
        } catch(e) { showToast("Ошибка X-PLATFORM API"); }
    }

    function renderTable(files = cachedFiles) {
        const container = document.getElementById('file-body');
        container.innerHTML = files.length ? '' : '<tr><td colspan="3" style="text-align:center; padding:150px; color:#aaa;">Папка пуста</td></tr>';
        
        files.forEach(item => {
            const tr = document.createElement('tr');
            tr.className = 'file-row';
            const isFolder = item.mimeType.includes('folder');
            
            tr.innerHTML = \`
                <td><i class="fa \${isFolder ? 'fa-folder' : 'fa-file-lines'}" style="margin-right:15px; color:\${isFolder ? '#fbc02d' : '#1a73e8'}; font-size:22px;"></i> \${item.name}</td>
                <td class="mobile-hide" style="color:var(--text-light); font-size:13px;">\${new Date(item.modifiedTime || Date.now()).toLocaleDateString('ru-RU')}</td>
                <td class="mobile-hide" style="color:var(--text-light); font-size:13px;">\${item.size ? (item.size/1024/1024).toFixed(2)+' MB' : '—'}</td>
            \`;

            tr.onclick = () => isFolder ? navigate(item.id, item.name) : uiPreview(item.id, item.name);
            tr.oncontextmenu = (e) => {
                e.preventDefault(); currentSelectedItem = item;
                const m = document.getElementById('context-menu');
                m.style.display = 'block'; m.style.left = e.clientX + 'px'; m.style.top = e.clientY + 'px';
            };
            container.appendChild(tr);
        });
    }

    function navigate(id, name) {
        const idx = pathHistory.findIndex(p => p.id === id);
        if(idx !== -1) pathHistory = pathHistory.slice(0, idx + 1); else pathHistory.push({id, name});
        refreshView(id);
        if(window.innerWidth < 768) document.getElementById('main-sidebar').classList.remove('mobile-open');
    }

    function updateBreadcrumbs() {
        document.getElementById('bc-path').innerHTML = pathHistory.map(p => \`<span class="bc-node" onclick="navigate('\${p.id}', '\${p.name}')">\${p.name}</span>\`).join(' <i class="fa fa-chevron-right" style="font-size:10px; opacity:0.3;"></i> ');
    }

    function filterFiles(query) {
        const filtered = cachedFiles.filter(f => f.name.toLowerCase().includes(query.toLowerCase()));
        renderTable(filtered);
    }

    function sortFiles(key) {
        if(sortState.key === key) sortState.asc = !sortState.asc;
        else { sortState.key = key; sortState.asc = true; }
        applySort();
        renderTable();
    }

    function applySort() {
        cachedFiles.sort((a, b) => {
            let valA = a[sortState.key]; let valB = b[sortState.key];
            if(sortState.key === 'size') { valA = parseInt(valA) || 0; valB = parseInt(valB) || 0; }
            if(sortState.asc) return valA > valB ? 1 : -1;
            return valA < valB ? 1 : -1;
        });
    }

    function toggleSidebarMenu() { document.getElementById('main-sidebar').classList.toggle('mobile-open'); }
    function toggleFabMenu(e) { e.stopPropagation(); const m = document.getElementById('action-menu'); m.style.display = m.style.display === 'block' ? 'none' : 'block'; }
    function uiUpload() { document.getElementById('real-file-input').click(); document.getElementById('action-menu').style.display='none'; }
    
    async function handleFileUpload(files) {
        for(let f of files) {
            showToast("X-CLOUD: Загрузка " + f.name);
            const fd = new FormData(); fd.append('file', f); fd.append('folderId', activeId);
            await fetch('/storage/api/v10/upload', {method: 'POST', body: fd});
        }
        refreshView(activeId);
    }

    async function uiMkdir() {
        const n = prompt("Название новой папки:"); if(!n) return;
        document.getElementById('action-menu').style.display='none';
        await fetch('/storage/api/v10/mkdir', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({parentId: activeId, name: n})});
        refreshView(activeId);
    }

    function uiPreview(id, name) {
        const tid = id || currentSelectedItem.id; const tname = name || (currentSelectedItem ? currentSelectedItem.name : 'Просмотр');
        document.getElementById('viewer-title').innerText = tname;
        document.getElementById('viewer-iframe').src = 'https://drive.google.com/file/d/' + tid + '/preview';
        document.getElementById('viewer').style.display = 'flex';
    }

    function closeViewer() { document.getElementById('viewer').style.display = 'none'; document.getElementById('viewer-iframe').src = ''; }
    
    async function uiDelete() {
        if(!confirm("X-PLATFORM: Удалить '" + currentSelectedItem.name + "'?")) return;
        await fetch('/storage/api/v10/delete/' + currentSelectedItem.id, {method: 'DELETE'});
        refreshView(activeId);
    }

    async function uiRename() {
        const n = prompt("Новое имя:", currentSelectedItem.name); if(!n || n === currentSelectedItem.name) return;
        await fetch('/storage/api/v10/rename', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({id: currentSelectedItem.id, name: n})});
        refreshView(activeId);
    }

    function uiInfo() {
        alert(\`Файл: \${currentSelectedItem.name}\\nID: \${currentSelectedItem.id}\\nТип: \${currentSelectedItem.mimeType}\\nРазмер: \${(currentSelectedItem.size/1024/1024).toFixed(2)} MB\`);
    }

    function showToast(text) { const b = document.getElementById('toast'); b.innerText = text; b.style.display = 'block'; setTimeout(() => b.style.display = 'none', 4000); }
    
    // Drag and Drop
    const zone = document.getElementById('drop-zone');
    zone.ondragover = (e) => { e.preventDefault(); zone.style.background = '#f0f7ff'; };
    zone.ondragleave = () => { zone.style.background = '#fff'; };
    zone.ondrop = (e) => { e.preventDefault(); zone.style.background = '#fff'; handleFileUpload(e.dataTransfer.files); };

    window.onclick = () => { document.getElementById('action-menu').style.display = 'none'; document.getElementById('context-menu').style.display = 'none'; };

    refreshView('root');
</script>
</body>
</html>
    `;

    // --- БЛОК 3: BACKEND API (ULTIMATE SYNCHRONIZER) ---

    // ГЛАВНЫЙ ТОЧКА ВХОДА (Убирает белый экран)
    app.get('/', (req, res) => res.send(UI));
    app.get('/storage', (req, res) => res.send(UI));

    // API: Продвинутый листинг с обучением
    app.get('/storage/api/v10/list', async (req, res) => {
        try {
            const folderId = req.query.folderId || 'root';
            let query = "";
            if (folderId === 'trash') query = "trashed = true";
            else if (folderId === 'sharedWithMe') query = "sharedWithMe = true and trashed = false";
            else query = `'${folderId}' in parents and trashed = false`;

            const r = await drive.files.list({
                q: query,
                fields: 'files(id, name, mimeType, size, modifiedTime, parents)',
                orderBy: 'folder, name'
            });

            // ОБУЧЕНИЕ: Запоминаем структуру автоматически
            for (const file of r.data.files) {
                await xBrainLearn(file, folderId, 'SCAN_SYNC');
            }

            res.json(r.data.files);
        } catch (e) {
            console.error("API List Error:", e.message);
            res.status(500).json({error: e.message});
        }
    });

    // API: Загрузка с регистрацией логики
    app.post('/storage/api/v10/upload', upload.single('file'), async (req, res) => {
        try {
            const driveFile = await drive.files.create({
                resource: { name: req.file.originalname, parents: [req.body.folderId] },
                media: { mimeType: req.file.mimetype, body: fs.createReadStream(req.file.path) },
                fields: 'id, name, mimeType, parents, size'
            });

            // ОБУЧЕНИЕ: Запоминаем загрузку
            await xBrainLearn(driveFile.data, req.body.folderId, 'USER_UPLOAD');

            if (fs.existsSync(req.file.path)) fs.unlinkSync(req.file.path);
            res.sendStatus(200);
        } catch (e) {
            res.status(500).send(e.message);
        }
    });

    // API: Создание папки
    app.post('/storage/api/v10/mkdir', express.json(), async (req, res) => {
        try {
            const folder = await drive.files.create({
                resource: { 
                    name: req.body.name, 
                    mimeType: 'application/vnd.google-apps.folder', 
                    parents: [req.body.parentId] 
                },
                fields: 'id, name, mimeType, parents'
            });

            // ОБУЧЕНИЕ: Запоминаем структуру
            await xBrainLearn(folder.data, req.body.parentId, 'USER_MKDIR');

            res.sendStatus(200);
        } catch (e) {
            res.status(500).send(e.message);
        }
    });

    // API: Переименование
    app.post('/storage/api/v10/rename', express.json(), async (req, res) => {
        try {
            await drive.files.update({ fileId: req.body.id, resource: { name: req.body.name } });
            res.sendStatus(200);
        } catch (e) {
            res.status(500).send(e.message);
        }
    });

    // API: Удаление
    app.delete('/storage/api/v10/delete/:id', async (req, res) => {
        try {
            await drive.files.update({ fileId: req.params.id, resource: { trashed: true } });
            res.sendStatus(200);
        } catch (e) {
            res.status(500).send(e.message);
        }
    });

    console.log("🚀 X-PLATFORM v65.0 ULTIMATE: СИСТЕМА ОБУЧЕНИЯ ПРИВЯЗАНА К server.js");
};
